arch: s390x

jobs:
  include:
  - name: dest-and-lang-default
  - dist: xenial
    name: xenial-lang-default
  - dist: bionic
    name: bionic-lang-default
  - dist: xenial
    name: xenial-ruby
    language: ruby
  - dist: bionic
    name: bionic-ruby
    language: ruby
  - dist: xenial
    name: xenial-c
    language: c
  - dist: bionic
    name: bionic-c
    language: c
  - dist: xenial
    name: xenial-minimal
    language: minimal
  - dist: bionic
    name: bionic-minimal
    language: minimal
  - dist: xenial
    name: xenial-slim
    language: slim
  - dist: bionic
    name: bionic-slim
    language: slim

install: skip

script:
# Environment information
- echo "==> Environment information"
- uname -a
- cat /etc/os-release
- grep ^processor /proc/cpuinfo
- free -m
- df -h

# Snaps
- echo "==> Snaps"
- sudo snap install core || true
- sudo snap install core
- sudo snap install hello-world
- hello-world

# Sleep
#- sleep 600

# Docker
- echo "==> Docker"
- docker info
- docker run hello-world

# # # ruby
# # - echo "==> Ruby"
# # - ruby -v
# # - gem i bundler
# # #- sleep 120
